#:schema node_modules/wrangler/config-schema.json
name = "xget-adult"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "xget-adult.uni-kui.shop/*"
zone_name = "uni-kui.shop"

[observability]
enabled = true
head_sampling_rate = 1
[placement]
mode = "smart"
