#:schema node_modules/wrangler/config-schema.json
name = "xget"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# 自定义域名配置
# 取消注释并修改为你的域名
# routes = [
#   { pattern = "your-domain.com/*", zone_name = "your-domain.com" },
#   { pattern = "*.your-domain.com/*", zone_name = "your-domain.com" }
# ]

[observability]
enabled = true
head_sampling_rate = 1
[placement]
mode = "smart"
