#:schema node_modules/wrangler/config-schema.json
name = "xget_adult"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "xget.loadingi.cloudns.be/*"
zone_name = "loadingi.cloudns.be"

[observability]
enabled = true
head_sampling_rate = 1
[placement]
mode = "smart"
